### ISSUE TITLE
deepmerge function not working with PartialDeep

### ISSUE THREAD

**Issue by willieseabrook** [RebeccaStevens/deepmerge-ts#22]
Note: Amazing library with amazing visual explanation of how it works!

# Bug Report

When calling deepmerge using two objects, one of type T and the other of type PartialDeep<T> from module type-fest, the result returned is PartialDeep<T>, which is clearly wrong.

However, if we use a deep clone from module rfdc on the objects first, before trying to merge, then the merge works correctly.

Example pseudocode:

```
this.defaultConfig = {
   one: {
      a: {
        name: 'test'
        location: 'city'
      }
    }
    two: {
      deep: {
        value: 'ok'
        another: 'cool'
      }
    }
}

this.override = {
    two: {
      deep: {
        value: 'ok'
      }
    }
}
```

```
import { PartialDeep } from "type-fest"

private override?: PartialDeep<T>

getDefaultConfig(): T {
  if (this.override == undefined) {
    return this.defaultConfig
  }

  const merged = deepmerge(this.defaultConfig, this.override)
  console.log(merged)
  return (merged as T)
}
```

## Expected behavior

deepmerge returns override deep merged into defaultConfig

## Actual behavior

deepmerge returns override

## Workaround

Use rfdc to deep clone the objects first. This works and produces the correct behavior.

```
const clone = require('rfdc')()

getDefaultConfig(): T {
  if (this.override == undefined) {
    return this.defaultConfig
  }

  const clonedDefaults = clone(this.defaultConfig)
  const clonedOverride = clone(this.override)

  const merged = deepmerge(clonedDefaults, clonedOverride)
  console.log(merged)
  return (merged as T)
}
```

**Comment by RebeccaStevens** [comment]
Could you elaborate on the issue?

I've manage to recreate the type issue where `DeepMergeHKT<[T, PartialDeep<T>], DeepMergeMergeFunctionsDefaultURIs>` equals `PartialDeep<T>` instead of `T`.

But I'm not sure on the value issue and the workaround you are reporting. The following does not throw for me:

```ts
import assert from "assert";

assert.deepEqual(
  deepmerge(this.defaultConfig, this.override),
  deepmerge(clonedDefaults, clonedOverride)
);
```
