### ISSUE TITLE
Being able to merge an array of objects

### ISSUE THREAD

**Issue by rbalet** [RebeccaStevens/deepmerge-ts#255]
# Suggestion
Like the old [deepmerge](https://github.com/TehShrike/deepmerge) library, being able to merge an array of object would be useful.

https://github.com/TehShrike/deepmerge

## Use case
[here](https://github.com/rbalet/ngx-translate-multi-http-loader/blob/master/projects/multi-http-loader/src/lib/multi-http-loader.ts) an example of the why I would need it.

I'm actually using `deepmerge` for that purpose

**Comment by rbalet** [comment]
If it help, this would be the required code.  

But I'm not sure about which type to use so I let you implement that one

```typescript
function deepmergeAll(array, options?: any) {
    if (!Array.isArray(array)) {
      throw new Error('first argument should be an array')
    }

    return array.reduce(function (prev, next) {
      return deepmerge(prev, next)
    }, {})
  }
}
```

**Comment by RebeccaStevens** [comment]
You can use the spread operator to do this:

```ts
const merged = deepmerge(...arrayOfObjects);
```
