### ISSUE TITLE
Merge B to A keep structure of B and only mutate original A object

### ISSUE THREAD

**Issue by rendomnet** [RebeccaStevens/deepmerge-ts#259]
# Suggestion
I have 2 objects and I want to mutate object "A" to get all changes from "B" and keep all unmodified original "A" fields. So result should be mutated object A but with changes from object B not a new object.
Is this possible with deeepmerge-ts?

```
const a = {
  record: {
    name: "John",
    color: "green",
    size: "medium",
    list: ['apple']
    age: 5
  }
};

const b = {
  record: {
    name: "John",
    color: "red"
    list: ['banana','potato']
  }
};

merge(a,{...b})
```

// return original object A with changes from B
```
{
 record: {
    name: "John", // original value from A
    color: "red", // changed value
    list: ['banana','potato'], // changed value
    age: 5  // original value 
  }
}
```

**Comment by RebeccaStevens** [comment]
This is a planned feature, but it's not yet implemented (#51)
