### ISSUE TITLE
Safari on bigSur 11.0.1

### ISSUE THREAD

**Issue by saiballo** [RebeccaStevens/deepmerge-ts#411]
## Bug Report

Console error also with example in doc:

`TypeError: values.at is not a function. (In 'values.at(-1)', 'values.at' is undefined)`

### Expected behavior

no console error :-)

### Actual behavior

`TypeError: values.at is not a function. (In 'values.at(-1)', 'values.at' is undefined)`

### Steps to reproduce

use it in safari:

```
const x = {
		record: {
		  prop1: "value1",
		  prop2: "value2",
		},
		array: [1, 2, 3],
		set: new Set([1, 2, 3]),
		map: new Map([
		  ["key1", "value1"],
		  ["key2", "value2"],
		]),
	  };

	  const y = {
		record: {
		  prop1: "changed",
		  prop3: "value3",
		},
		array: [2, 3, 4],
		set: new Set([2, 3, 4]),
		map: new Map([
		  ["key2", "changed"],
		  ["key3", "value3"],
		]),
	  };

	  const merged = deepmerge(x, y);

	  console.log(merged);
```

**Comment by RebeccaStevens** [comment]
This repo uses es2020. The particular function that not working was added in Safari 12 (https://caniuse.com/?search=Array.at).

If you need support for older version of safari, you'll need to down level this library using tools suchs as [babel](https://babeljs.io/).

**Comment by fritzfelix** [comment]
@RebeccaStevens The `Array.at` function was not added in Safari 12, but 15, this is correct link to the function: https://caniuse.com/mdn-javascript_builtins_array_at

I would like to reopen the discussion around this https://github.com/RebeccaStevens/deepmerge-ts/issues/487.
