### ISSUE TITLE
Discriminated union types

### ISSUE THREAD

**Issue by mdoury-oef** [RebeccaStevens/deepmerge-ts#435]
#### Merging objects typed as a discriminated union breaks type discrimination.

The type inferred from the merge of two or more objects typed as a [discriminated union](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-func.html#discriminated-unions) cannot be narrowed down by TypeScript. 

### Expected behavior

```typescript
import { deepmerge } from "deepmerge-ts"

type FOO = { a: true; b: string } | { a: false; b: number }

declare const foo: FOO
declare const bar: FOO
const baz = deepmerge(foo, bar)

if (foo.a) {
    foo.b // string
}

if (baz.a) {
    baz.b // string
}
```

### Actual behavior

```typescript
import { deepmerge } from "deepmerge-ts"

type FOO = { a: true; b: string } | { a: false; b: number }

declare const foo: FOO
declare const bar: FOO
const baz = deepmerge(foo, bar)

if (foo.a) {
    foo.b // string
}

if (baz.a) {
    baz.b // string | number
}
```

### Failing `tsd` test

```typescript
type V = { a: true; b: string } | { a: false; b: number };
const n = { a: true, b: "n" };
const o = { a: false, b: "o" };

const test17 = deepmerge(n as V, o as V);
if (test17.a) {
  expectType<string>(test17.b);
}
```

**Comment by RebeccaStevens** [comment]
I don't think keeping discriminated unions can be done without breaking things.

For example, if we take your test above but tweak it like so:

```ts
type V = { a: true; b: string } | { a: false; b?: number };
const n: V = { a: true, b: "n" };
const o: V = { a: false };

const test17 = deepmerge(n, o);
console.log(test17.a); // false
console.log(test17.b); // "n"
```

You can see that `test17.a` being `false`, does not inform us that `test17.b` is `number | undefined`, because it is in fact `string`.

However, in looking into this, I did discover a bug as `test17.b` is being typed as `number | undefined` here.

**Comment by RobertSandiford** [comment]
deepmerge-ts is an npm package, not a part of TypeScript. TypeScript does not provide a tool to produce an output type from such an operation, so the output is generated by deepmerge-ts using type logic. Therefore this is an deepmerge-ts issue not a TypeScript issue.
