### ISSUE TITLE
Looking for a way to restore the old undefined replacing values behavior 

### ISSUE THREAD

**Issue by tim-field** [RebeccaStevens/deepmerge-ts#478]
We need a way to restore the behavior that was present before #449 merged.  Is there a recommended approach here?

Thanks

**Comment by RebeccaStevens** [comment]
[docs/deepmergeCustom.md#filtering-values](https://github.com/RebeccaStevens/deepmerge-ts/blob/main/docs/deepmergeCustom.md#filtering-values)

> ```ts
> import {
>   type DeepMergeNoFilteringURI,
>   deepmergeCustom,
> } from "deepmerge-ts";
> 
> const customizedDeepmerge = deepmergeCustom<
>   unknown,
>   {
>     DeepMergeFilterValuesURI: DeepMergeNoFilteringURI;
>   }
> >({
>   filterValues: false,
> });
> ```

**Comment by tim-field** [comment]
Thank you 🙏
