### ISSUE TITLE
`mergeOthers` example from docs doesn't work

### ISSUE THREAD

**Issue by nvlang** [RebeccaStevens/deepmerge-ts#482]
## Bug Report

The example below from the docs doesn't work.

https://github.com/RebeccaStevens/deepmerge-ts/blob/4a73737203cb0a0e4703ea50c4f91b44c740eca1/docs/deepmergeCustom.md?plain=1#L185-L235

### Expected behavior

No type errors.

### Actual behavior

```
example.ts:20:44 - error TS2554: Expected 2 arguments, but got 1.

20         return utils.defaultMergeFunctions.mergeOthers(values);
                                              ~~~~~~~~~~~

  node_modules/.pnpm/deepmerge-ts@7.0.2/node_modules/deepmerge-ts/dist/node/index.d.mts:626:95
    626 declare function mergeOthers<Ts extends ReadonlyArray<unknown>>(m_target: Reference<unknown>, values: Ts): void;
                                                                                                      ~~~~~~~~~~
    An argument for 'values' was not provided.


Found 1 error in example.ts:20
```

Minimal reproduction: https://github.com/nvlang/deepmerge-ts-bug

---

I noticed this after getting some linter warnings/errors after updating `deepmerge-ts` from `5.1.0` to `7.0.2`, because I used `deepmergeCustom` to create a merge function which filters out undefined and null values, and doesn't merge arrays (overriding them instead):

```ts
export const mergeCustom = deepmergeCustom({
    mergeOthers: (values, utils) =>
        utils.defaultMergeFunctions.mergeOthers(
            values.filter((v) => v !== undefined && v !== null),
        ),
    // Don't merge arrays
    mergeArrays: (values) => values[values.length - 1],
});
```

I checked the CHANGELOG.md for breaking changes, and saw a note about the generics around deepmergeCustom having changed:

> The order of the generics of `deepmergeCustom` and `deepmergeIntoCustom` have changed. If you are passing generics to these functions you need to update them. [[Source](https://github.com/RebeccaStevens/deepmerge-ts/blob/4a73737203cb0a0e4703ea50c4f91b44c740eca1/CHANGELOG.md#breaking-changes-1)]

However, in my case I wasn't passing any type parameters, so I didn't think I'd have to change anything.

Clarification regarding this would be much appreciated, but, in any event, thank you for your work on a great library!

**Comment by RebeccaStevens** [comment]
Looks like its just a type error. I'll get that fixed.
If you run the code, it should work.

**Comment by RebeccaStevens** [comment]
Hmmm, interesting. Looks like a bug in the bundling process.

**Comment by RebeccaStevens** [comment]
Bug reported to upstream: https://github.com/wessberg/rollup-plugin-ts/issues/226
I should be able to add a workaround for now.
