### ISSUE TITLE
[Typing] unknown type when using js spread on array

### ISSUE THREAD

**Issue by Pavel-Boyazov** [RebeccaStevens/deepmerge-ts#484]
## Bug Report
When i use spread on type with undefined-length array with objects type of merged object is `unknown` but result is right

### Expected behavior
Right type when use spread

### Actual behavior
`unknown` type when use spread

### Steps to reproduce

Try this code:
```js
const { deepmerge } = require("deepmerge-ts");

const arr = [{ example: true }, { example: false }]; // Type: `{ example: boolean; }[]`
const obj = deepmerge(...arr); // Type: `unknown`

console.log(obj); // { example: false }
```
P.s. I use js. Not ts

**Comment by RebeccaStevens** [comment]
Passing an array (typed as an array) to deepmerge doesn't give us enough information about the types for us to determine the type so we just use `unknown` in this case.

For us to have enough information in this case, you'd need to type the array as a tuple.

In typescript this can be done with `as const`:
```ts
const arr = [{ example: true }, { example: false }] as const;
```

And in javascript with:
```js
const arr = /** @type {const} */ [{ example: true }, { example: false }];
```
