### ISSUE TITLE
Remove Array.at

### ISSUE THREAD

**Issue by fritzfelix** [RebeccaStevens/deepmerge-ts#487]
## Suggestion

Hey,
we came across the issue of clients not supporting `Array.at` ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at)), which this library utilizes. The number of clients not supporting it was so significant, that we can not use this library at the moment without polyfills, which we would like to avoid due to the additional complexity.

It seems a new-ish feature, that Safari only got in May 2022 according to [caniuse](https://caniuse.com/mdn-javascript_builtins_array_at).

I would kindly request using an alternative method with broader browser support.

**Comment by RebeccaStevens** [comment]
You shouldn't rely on your dependencies natively supporting your targeted platforms.

If you need to support older versions of Safari, then you should either polyfill your code as you mention or better yet downlevel your build.

The polyfill is the most straightforward as it's literally just a one-line function you need to include in your project somewhere:

```js
Array.prototype.at ??= function(value) {
  return this[value < 0 ? this.length + value : value];
}
```

If you don't want to polyfill, you could just patch the dependency using `pnpm patch` (or with [patch-package](https://www.npmjs.com/package/patch-package) if you're using `npm`).
