### ISSUE TITLE
Add DeepmergeInto

### ISSUE THREAD

**Issue by RebeccaStevens** [RebeccaStevens/deepmerge-ts#51]
### Discussed in https://github.com/RebeccaStevens/deepmerge-ts/discussions/49

<div type='discussions-op-text'>

<sup>Originally posted by **NightProgramming** February 15, 2022</sup>
Sometimes it's useful to not create a new merge result object, but to have an existing object, that is the target of the whole merging process. Right now, I think, I would have to do something like:

```
// We want to merge newestData into myDataObject:

const result = deepmerge(myDataObject, newestData);
Object.assign(myDataObject, result);
```

If there was a signature like `deepmerge(target, ...sources)` the performance might be better because no intermediate object (`result`) needs to be created. Also there would be less code required (no Object.assign). And if we don't want to merge into any existing object we could do `const result = deepmerge({}, myDataObject, newestData));`. Note: The return value is the same object we used as first argument. Without having it returned by deepmerge we would need a bit more code: `const result = {}; deepmerge(result, myDataObject, newestData);`</div>

**Comment by bombillazo** [comment]
This feature would be great! Im needing it at the moment :)

**Comment by rendomnet** [comment]
Count me in!
