### ISSUE TITLE
deepmergeIntoCustom returns undefined

### ISSUE THREAD

**Issue by NikolaRHristov** [RebeccaStevens/deepmerge-ts#520]
When using `deepmergeIntoCustom` with the default options it returns `undefined`. It is properly logging the values though:

https://codesandbox.io/p/sandbox/deepmerge-ts-example-forked-64vgnm?file=%2Fsrc%2Fexample.ts%3A7%2C10

**Comment by RebeccaStevens** [comment]
`deepmergeIntoCustom` will always return `undefined`. It modifies the first value instead of returning something.

**Comment by RebeccaStevens** [comment]
use `deepmergeCustom` if you don't want to modify the value, and want a result returned instead.
