### ISSUE TITLE
Merge non-existing fields

### ISSUE THREAD

**Issue by hriiss** [RebeccaStevens/deepmerge-ts#522]
I am wondering if this is possible, as I haven't seen it in the docs.
I want to merge 2 objects y1 and y2.
If I do:
`deepmerge(y1, y2)`
and y2 has some fields that don't exist in y1, it wont override or **add** them at all.
I am wondering if it's possible to change this.
Thank you.

**Comment by RebeccaStevens** [comment]
The result of the merge should have all the fields of `y1` and `y2`.
If you want `y1` to be modified to have the fields of `y2`, you need to you `deepmergeInto`

```js
const x = deepmerge(y1, y2);
```
https://codesandbox.io/p/sandbox/deepmerge-ts-example-forked-nx5sp7

```js
deepmergeInto(y1, y2);
```
https://codesandbox.io/p/sandbox/deepmerge-ts-example-forked-t9y227

**Comment by hriiss** [comment]
> The result of the merge should have all the fields of `y1` and `y2`. If you want `y1` to be modified to have the fields of `y2`, you need to use `deepmergeInto`
> 
> ```js
> const x = deepmerge(y1, y2);
> ```
> 
> https://codesandbox.io/p/sandbox/deepmerge-ts-example-forked-nx5sp7
> 
> ```js
> deepmergeInto(y1, y2);
> ```
> 
> https://codesandbox.io/p/sandbox/deepmerge-ts-example-forked-t9y227

If I merge y1 and y2, I want to overwrite the fields in y1 with the existing fields of y2.
Any other field that doesn't exist should be added from y1.
Is this somehow possible?

Example:
```js
const y1 = {
field1: "value1",
field2: {
  a: 0,
  b: 1
}

const y2 = {
field1: "newvalue",
field3: "newvalue2"
}

Output:
{
field1: "newvalue",
field2: {
  a: 0,
  b: 1
},
field3: "newvalue2"
}
```

**Comment by RebeccaStevens** [comment]
That's exactly how it works:

https://codesandbox.io/p/sandbox/deepmerge-ts-example-forked-nx5sp7

**Comment by hriiss** [comment]
> That's exactly how it works:
> 
> https://codesandbox.io/p/sandbox/deepmerge-ts-example-forked-nx5sp7

Thank you for showing me an example.
It seems like there was an error on my side with how I fetched the object I wanted to merge into.
