### ISSUE TITLE
🐛Deepmerge-ts now making typescript build hang / not responding

### ISSUE THREAD

**Issue by fatihaziz** [RebeccaStevens/deepmerge-ts#94]
# Bug Report
It's started since last week, when I try to compile my typescript, 
`tsc`
something wrong happen, it never done. something is stuck.

I tried to reinstall all node_modules, clean NPM cache, lastly I uninstall my node and change to version 16.14.2
none of them works...

then today, I try to install all my dependencies one by one and see if the tsc running / atleast throwing error.
when it comes to remove deepmerge-ts. it works, my tsc throwing error module not found.

having dependency to deepmerge-ts:
![image](https://user-images.githubusercontent.com/23287658/161784876-f0980ce2-bb79-4bdb-925f-e90a5f98455f.png)

after removing
![image](https://user-images.githubusercontent.com/23287658/161785271-73f4426f-c0f6-4447-a83a-4d909dc60d88.png)

I tried with all version deepmerge-ts@3, @2, and @1, none of them work...

deepmerge-ts is awesome library that I need for my project, I hope it can be solved.

## Expected behavior
Won't affect to tsc compiler behavior

## Actual behavior
It make tsc compiler stuck

## Steps to reproduce
1. `npm i deepmerge-ts`
2. `npm run build` or `tsc`
3. getting stuck

## System Environtment
- OS: Windows 11
- NodeJS: 16.14.2, 14.17.6
- Typescript: 4.4.2, 4.4.4, 4.6.3
- npm: 6, 8.5

## Files:
tsconfig.json:
```
{
	"compileOnSave": true,
	"compilerOptions": {
		"composite": true,
		"baseUrl": "./",
		"outDir": "./lib",
		"declaration": true,
		"declarationDir": "./@types",
		"declarationMap": true,
		"target": "ES6",
		"module": "CommonJS",
		"lib": [
			"ES6",
			"ES2018",
			"ESNext",
			"DOM"
		],
		"strict": true,
		"strictPropertyInitialization": false,
		"noImplicitAny": false,
		"noImplicitThis": false,
		"pretty": true,
		"sourceMap": true,
		"allowJs": true,
		"noEmit": false,
		"moduleResolution": "node",
		"allowSyntheticDefaultImports": true,
		"forceConsistentCasingInFileNames": true,
		"esModuleInterop": true,
		"experimentalDecorators": true,
		"emitDecoratorMetadata": true,
		"useUnknownInCatchVariables": false,
		"removeComments": true,
		"typeRoots": [
			"src/@types",
			"node_modules/@types"
		]
	},
	"include": [
		"src/**/*.ts"
	],
	"exclude": [
		"dist",
		"lib",
		"node_modules",
		"tests",
		"*deprecated*",
		"*ignore*"
	]
}
```

**Comment by fatihaziz** [comment]
I forked the repo, https://github.com/fatihaziz/deepmerge-ts-es6/compare/main...fix/ts-issue-es6
and now somehow its working fine, no more hang or not responding. 

but, I still don't know the reason behind it, why the tsc compiler become not responding...

Could I upload [this](https://github.com/fatihaziz/deepmerge-ts-es6) into npm?

**Comment by RebeccaStevens** [comment]
Give me a bit and I'll see if I can resolve this.
Would you be able to provide a minimal repo that reproduces the issue?

**Comment by fatihaziz** [comment]
this is the minimal repo: [here](https://github.com/fatihaziz/deepmerge-ts-compile-issue)

**Comment by RebeccaStevens** [comment]
Just started looking into this now.
I haven't found the exact cause of the problem yet but the issue goes away it you use `"skipLibCheck": true` in your project's `tsconfig.json`

**Comment by fatihaziz** [comment]
If we set the `skipLibCheck: true` typescript compiler will ignore descrepancy from the dependencies types.

Typescript server won't bother checking the types error from modules anymore. Which we won't like to do. 

I think the problem is from the v04 types generated by rollup. But i never use rollup before, so i dont know what the purpose of it.

**Comment by RebeccaStevens** [comment]
What I've found so far it that it seems to be this type declaration that is causing the hang.

https://github.com/RebeccaStevens/deepmerge-ts/blob/4b6b64dad22a6a926a2343ed914f6fbeb282bff1/dist/node/types/current/index.d.ts#L389

I don't know why yet.

**Comment by fatihaziz** [comment]
Maybe its goes like this:
1. deepmerge-ts types which generated is occuring a loophole for typescript compiler.
2. No error when compiling on the deepmerge-ts side. 
3. then, when it published. someone install it, and try to compile it, the typescript will fall into the loophole.
And the compiler stuck.

Its weird and mindblowing for me since how types can make the compiler fall into indefinitely loophole.

This is indicated by my laptop performance when i try to compile it, the fan speed rise up higher than usually. 
Which it rarely happen on normal build, that indicates there is some resource intensive task when compiling.
I try to make indefinitely while loop and run on browser and have same indication.

**Comment by RebeccaStevens** [comment]
I'm trying to debug tsc atm to see what is going on. It's possible this is an upstream problem with TypeScript itself.

**Comment by fatihaziz** [comment]
Alright, i will wait for the updates then.

**Comment by RebeccaStevens** [comment]
So I'm not sure exactly what is going on but I think it is to do with the type complexity.
The type shouldn't actually be that complex, it should be aliased.
