### ISSUE TITLE
Expecting deepmerge-ts default to existing value, instead of overwriting with undefined,

### ISSUE THREAD

**Issue by fatihaziz** [RebeccaStevens/deepmerge-ts#96]
# Bug Report
Usually when i use deepmerge-ts it will ignore if first object value is populated with anything but undefined, and second object has undefined value, it will ignore it and leave the first object value as it.

example:
```
const default = {
  "somekey" : {
     "populated": "im populated"
  }
}
const b = {
  "somekey": {
    "populated": void 0,
  },
  "keyb": true
}

const deepmerge = deepmergeCustom({ mergeArrays: false });
const result = deepmerge(default,b)
```

I'm expecting the result will be:
```
{
  "somekey": {
    "populated": "im populated",
  },
  "keyb": true
}
```

but instead I got:
```
{
  "somekey": {
    "populated": undefined,
  },
  "keyb": true
}
```

here the sandbox code: https://stackblitz.com/edit/typescript-58wd1f?file=main.ts

## Expected behavior
should work as expected, ignoring undefined value

## Actual behavior
populated value got overwrite by undefined,

## Steps to reproduce
here the sandbox code: https://stackblitz.com/edit/typescript-58wd1f?file=main.ts

## Proposed changes
if its on purpose, I propose there is an option to make it work, like `mergeSkipUndefined:true`
then it will opted out all undefined values before merging.

**Comment by RebeccaStevens** [comment]
This is by design. Here's a custom merge that has your desired effect: #25

I'm open to possibly including that version of deep merge in the library itself but I'm not sure what would be the best way to do so.
